export const payrollDataTable = [
  {
    id: "EMP001",
    name: "John Doe",
    department: "Development",
    bankName: "HDFC Bank",
    accountNumber: "XXXXXXXX1234",
    ifsc: "HDFC0001234",
    amount: "$5,000.00",
    status: "Processed",
  },
  {
    id: "EMP002",
    name: "Sarah Wilson",
    department: "HR",
    bankName: "ICICI Bank",
    accountNumber: "XXXXXXXX9981",
    ifsc: "ICIC0009876",
    amount: "$4,200.00",
    status: "Pending",
  },
  {
    id: "EMP003",
    name: "Michael Smith",
    department: "Sales",
    bankName: "Axis Bank",
    accountNumber: "XXXXXXXX5567",
    ifsc: "UTIB0006754",
    amount: "$3,900.00",
    status: "Failed",
  },
  {
    id: "EMP004",
    name: "Priya Sharma",
    department: "Marketing",
    bankName: "SBI",
    accountNumber: "XXXXXXXX4477",
    ifsc: "SBIN0002201",
    amount: "$4,800.00",
    status: "Processed",
  },
  {
    id: "EMP005",
    name: "Anil Kumar",
    department: "Support",
    bankName: "Kotak Bank",
    accountNumber: "XXXXXXXX8899",
    ifsc: "KKBK0001133",
    amount: "$3,500.00",
    status: "Pending",
  },
  {
    id: "EMP006",
    name: "Nisha Verma",
    department: "Finance",
    bankName: "HDFC Bank",
    accountNumber: "XXXXXXXX3377",
    ifsc: "HDFC0004412",
    amount: "$6,200.00",
    status: "Processed",
  },
  {
    id: "EMP007",
    name: "Karan Patel",
    department: "IT Support",
    bankName: "Axis Bank",
    accountNumber: "XXXXXXXX6655",
    ifsc: "UTIB0001133",
    amount: "$4,000.00",
    status: "Pending",
  },
  {
    id: "EMP008",
    name: "Sneha Reddy",
    department: "Testing",
    bankName: "SBI",
    accountNumber: "XXXXXXXX7788",
    ifsc: "SBIN0003567",
    amount: "$4,500.00",
    status: "Processed",
  },
  {
    id: "EMP009",
    name: "Arjun Mehta",
    department: "Design",
    bankName: "ICICI Bank",
    accountNumber: "XXXXXXXX2255",
    ifsc: "ICIC0002244",
    amount: "$3,800.00",
    status: "Failed",
  },
  {
    id: "EMP010",
    name: "Divya Sharma",
    department: "Admin",
    bankName: "HDFC Bank",
    accountNumber: "XXXXXXXX9911",
    ifsc: "HDFC0001122",
    amount: "$4,900.00",
    status: "Processed",
  },
];
