// src/data/payrollData.js
export const payrollData = [
  {
    id: 'EMP001',
    name: 'Rajesh Kumar',
    department: 'Development',
    bankName: 'HDFC Bank',
    accountNumber: '******1234',
    ifscCode: 'HDFC0001234',
    creditAmount: '₹48,500',
    status: 'Processed',
  },
  {
    id: 'EMP002',
    name: 'Priya Sharma',
    department: 'Design',
    bankName: 'ICICI Bank',
    accountNumber: '******5678',
    ifscCode: 'ICIC0005678',
    creditAmount: '₹36,200',
    status: 'Draft',
  },
  {
    id: 'EMP003',
    name: 'Amit Patel',
    department: 'Marketing',
    bankName: 'SBI',
    accountNumber: '******9012',
    ifscCode: 'SBIN0009012',
    creditAmount: '₹52,000',
    status: 'Hold',
  },
    {
    id: 'EMP004',
    name: 'Amit Patel',
    department: 'Marketing',
    bankName: 'SBI',
    accountNumber: '******9012',
    ifscCode: 'SBIN0009012',
    creditAmount: '₹52,000',
    status: 'Hold',
  },
    {
    id: 'EMP005',
    name: 'Amit Patel',
    department: 'Marketing',
    bankName: 'SBI',
    accountNumber: '******9012',
    ifscCode: 'SBIN0009012',
    creditAmount: '₹52,000',
    status: 'Hold',
  },
    {
    id: 'EMP006',
    name: 'Amit Patel',
    department: 'Marketing',
    bankName: 'SBI',
    accountNumber: '******9012',
    ifscCode: 'SBIN0009012',
    creditAmount: '₹52,000',
    status: 'Hold',
  },
  
  // Add more rows as needed
];