// src/Applicants/applicantsData.js

export const applicants = [
  {
    id: 1,
    name: 'Alice Johnson',
    email: 'alice.johnson@email.com',
    phone: '+1 (555) 123-4567',
    appliedFor: 'Senior Software Engineer',
    appliedDate: '2024-01-18',
    experience: '6 years',
    location: 'New York, NY',
    stage: 'Application',
    status: 'Under Review',
    source: 'LinkedIn',
    resume: 'alice_johnson_resume.pdf',
    coverLetter: 'alice_johnson_cover.pdf',
    skills: ['JavaScript', 'React', 'Node.js', 'Python'],
    education: 'MS Computer Science - Stanford University',
    rating: 4.5,
    notes: 'Strong technical background with excellent communication skills',
    lastActivity: '2 hours ago'
  },
  {
    id: 2,
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    phone: '+1 (555) 234-5678',
    appliedFor: 'Senior Software Engineer',
    appliedDate: '2024-01-17',
    experience: '8 years',
    location: 'San Francisco, CA',
    stage: 'Shortlisted',
    status: 'Shortlisted',
    source: 'Company Website',
    resume: 'michael_chen_resume.pdf',
    coverLetter: 'michael_chen_cover.pdf',
    skills: ['Java', 'Spring', 'AWS', 'Docker'],
    education: 'BS Computer Engineering - UC Berkeley',
    rating: 5.0,
    notes: 'Exceptional candidate with leadership experience',
    lastActivity: '1 day ago'
  },
  {
    id: 3,
    name: 'Sarah Williams',
    email: 'sarah.williams@email.com',
    phone: '+1 (555) 345-6789',
    appliedFor: 'UX Designer',
    appliedDate: '2024-01-16',
    experience: '5 years',
    location: 'New York, NY',
    stage: 'Interview',
    status: 'Interview Scheduled',
    source: 'Referral',
    resume: 'sarah_williams_resume.pdf',
    coverLetter: 'sarah_williams_cover.pdf',
    skills: ['Figma', 'Sketch', 'Adobe Creative Suite', 'Prototyping'],
    education: 'BFA Design - Parsons School of Design',
    rating: 4.8,
    notes: 'Great portfolio demonstrating user-centered design approach',
    lastActivity: '3 hours ago'
  },
  {
    id: 4,
    name: 'David Rodriguez',
    email: 'david.rodriguez@email.com',
    phone: '+1 (555) 456-7890',
    appliedFor: 'Product Manager',
    appliedDate: '2024-01-15',
    experience: '7 years',
    location: 'Austin, TX',
    stage: 'Offer',
    status: 'Offer Extended',
    source: 'Indeed',
    resume: 'david_rodriguez_resume.pdf',
    coverLetter: 'david_rodriguez_cover.pdf',
    skills: ['Product Strategy', 'Agile', 'Analytics', 'Stakeholder Management'],
    education: 'MBA - Wharton School',
    rating: 4.9,
    notes: 'Strong product sense with proven track record of successful launches',
    lastActivity: '4 hours ago'
  },
  {
    id: 5,
    name: 'Emma Thompson',
    email: 'emma.thompson@email.com',
    phone: '+1 (555) 567-8901',
    appliedFor: 'Marketing Specialist',
    appliedDate: '2024-01-14',
    experience: '3 years',
    location: 'Remote',
    stage: 'Application',
    status: 'Rejected',
    source: 'Glassdoor',
    resume: 'emma_thompson_resume.pdf',
    coverLetter: '',
    skills: ['Digital Marketing', 'SEO', 'Content Marketing', 'Social Media'],
    education: 'BA Marketing - University of Texas',
    rating: 3.2,
    notes: 'Limited experience in B2B marketing which is required for this role',
    lastActivity: '1 week ago'
  },
  {
    id: 6,
    name: 'James Wilson',
    email: 'james.wilson@email.com',
    phone: '+1 (555) 678-9012',
    appliedFor: 'DevOps Engineer',
    appliedDate: '2024-01-13',
    experience: '6 years',
    location: 'Seattle, WA',
    stage: 'Interview',
    status: 'Technical Interview',
    source: 'Stack Overflow',
    resume: 'james_wilson_resume.pdf',
    coverLetter: 'james_wilson_cover.pdf',
    skills: ['Kubernetes', 'Docker', 'AWS', 'Terraform', 'Jenkins'],
    education: 'BS Information Systems - University of Washington',
    rating: 4.6,
    notes: 'Solid DevOps experience with cloud infrastructure expertise',
    lastActivity: '2 days ago'
  }
];
